#!/usr/bin/env python
#  Copyright (C) 2014  Instituto Nokia de Tecnologia - INdT
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
from __future__ import print_function
import argparse
from pprint import pprint
from target_format import *

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Parse nRF8001 setup data.")
    parser.add_argument("report", type=file,
            help="report generated by nRFgoStudio (ublue_setup.gen.out.txt)")
    args = parser.parse_args()

    version, setup_data = parse_setup(args.report)

    print("Setup Data:")
    pprint(setup_data)

    print("\nTarget 0x00:")
    target = Target_00.parse(setup_data[0x00].decode("hex"))
    print(target)
    assert target["dll_version"] == version
